[package]
name = "special-functions"
version = "0.1.0"
authors = ["JP-Ellis <josh@jpellis.me>"]

edition = "2018"

[dependencies]
GSL = "1.1"
log = "0.4"

[dev-dependencies]
csv = "1.1"

[features]
default = []
nightly = []
