[package]
name = "special-functions"
version = "0.1.0"
authors = ["JP-Ellis <josh@jpellis.me>"]

edition = "2018"

[dependencies]
log = "0.4.6"
GSL = "1.1.0"

[dev-dependencies]
csv = "1.0.5"

[features]
default = []
nightly = []
