name: Rust Coverage

on:
  pull_request:
    paths:
      - "**/*.rs"
      - "Cargo.toml"
  push:
    paths:
      - "**/*.rs"
      - "Cargo.toml"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Tarpaulin
        uses: actions-rs/tarpaulin@v0.1
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
